{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: {{ if .Values.rbac.clusterWideAccess }}"ClusterRole"{{ else }}"Role"{{ end }}
metadata:
  name: {{ template "zalenium.fullname" . }}
  labels:
    app: {{ template "zalenium.name" . }}
    chart: {{ template "zalenium.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
{{- end -}}
