apiVersion: v1
kind: Service
metadata:
  name: {{ template "zalenium.fullname" . }}
  labels:
    app: {{ template "zalenium.name" . }}
    role: grid
    chart: {{ template "zalenium.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.hub.serviceAnnotations }}
  annotations:
{{ toYaml .Values.hub.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.hub.serviceType | quote }}
{{- if eq .Values.hub.serviceType "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.hub.serviceSourceRanges }}
{{- end }}
  sessionAffinity: {{ .Values.hub.serviceSessionAffinity | quote }}
  ports:
  - name: hub
    port: {{ .Values.hub.port }}
    targetPort: {{ .Values.hub.port }}
  selector:
    app: {{ template "zalenium.name" . }}
    release: "{{ .Release.Name }}"
